version: '3'
name: 'crm-environment'

services:

  mysql:
    container_name: mysql-crm
    image: 'mysql:8.0.29'
    tty: true
    restart: unless-stopped
    networks:
      - web
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""

  admin:
    container_name: admin-crm
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - web
    environment:
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    ports:
      - "8181:8181"
    volumes:
      - './:/var/www/html'
    depends_on:
      - mysql

networks:
  web:
    external: true